version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  keycloak-container:
    image: jboss/keycloak:5.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
